# Configuration for factors

# main_force_flow
MAIN_FORCE_FLOW_THRESHOLD = 0.02

# atr factor
ATR_LOOKBACK = 14
ATR_VOL_WINDOW = 20
ATR_EXPAND_WINDOW = 20
ATR_LOW_VOL_THRESHOLD = 0.05
ATR_MED_VOL_THRESHOLD = 0.10
ATR_EXPANSION_MULTIPLIER = 1.3